### ISSUE TITLE
Javascript execution on browser create an empty page.

### ISSUE THREAD

**Issue by jaympatel1893** [t3nsor/quora-backup#2] opened 2015-04-03 21:07 UTC
I tried execution of the javascript on console of two browsers: Mozilla and Chrome. 
It opens a new tab with blank screens.

What is the issue?

**Comment by t3nsor** [comment] 2015-04-07 23:15
That's hard to say without more information. Does the console show any errors?

**Comment by jaympatel1893** [comment] 2015-04-08 16:40
Is it because I am using Windows?
Console error is :
TypeError: Array.prototype.map called on null or undefined

Any guidelines to achive this in windows?

**Comment by t3nsor** [comment] 2015-04-09 17:49
JavaScript should work the same on Windows. What does `$('.UserContentList .pagedlist_item')` return in the console for you?

**Comment by skrishnan22** [comment] 2016-01-07 18:09
Changing $('.UserContentList .pagedlist_item') to $('.AnswerListItem.PagedListItem.feed_item') worked for me,but the time stamp was empty.

**Comment by t3nsor** [comment] 2016-03-25 04:54
Still can't reproduce, so closing.

**Closed as completed** 2016-03-25 04:54 UTC
